name = input('enter the first line: ')
length = len(name)
print('this line has', length, 'word')
start = int(input('enter the start number: '))
end = int(input('enter the end number: '))
text = (name[start:end])
print(text)
